name: 'Batch Remote SSH Commands With Port'
description: 'help user sent batch ssh command to remote server node'
branding:
  color: 'red'
  icon: 'chevron-up'
author: 'wenchui'
inputs:
  ipaddr: 
    required: true
    description: 'the remote server node ip address'
  port: 
    required: false
    description: 'the remote server node login port'
    default: '22'
  username: 
    required: true
    description: 'the remote server node login username'
    default: 'service'
  password: 
    required: true
    description: 'the remote server node login password'
    default: '1234567890'
  commands: 
    required: true
    description: 'the batch remote ssh commands'
    default: |
             ls -la
             ps -ef | grep java
             whoami

runs:
  using: 'node16'
  main: 'dist/index.js'
